### ISSUE TITLE
SLB Video Handler not displaying Vimeo video

### ISSUE THREAD

**Issue by gfalken** [archetyped/slb-addons#22]
SLB Video Handler v0.1.0
SLB v2.3.1
http://sierramac.webdancers.com/yosemite-river-rafting-trips/cherry-creek-upper-tuolumne/
**Problem exists with no other plugins active and 2015 theme.**
Plugins currently active:
- Black Studio TinyMCE
- Constant Contact
- Cyclone Slider 2
- Easy Smooth Scroll Links
- Genesis Simple Edits
- Image Widget
- Imsanity
- MCE Table Buttons
- Ninja Forms
- Q&A Focus Plus FAQ
- Regenerate Thumbnails
- Reveal IDs
- Simple Lightbox
- Simple Lightbox: Video Handler
- Widget Logic
Issue occurs in current versions of Chrome, Firefox and IE

When the "Watch the Video" link is clicked, the lightbox and spinning icon is displayed but the video never loads.

**Comment by archetyped** [comment]
Hi, your site appears to be blocking requests to WordPress' `admin-ajax.php`.  Please check to make sure you don't have any plugins, themes, or settings that redirect requests to the home page, as this is causing your site's home page HTML to be sent to SLB instead of the Vimeo player HTML.

Please let me know what you find.

**Comment by gfalken** [comment]
I checked with the hosting company and it was triggering a mod sec rule, They added an exclusion for the rule on this domain and the video is now loading and playing without issue. Thanks for pointing me in the right direction.

**Comment by archetyped** [comment]
Hi, glad to hear your issue was resolved :)
