### ISSUE TITLE
[Video / Issue]: Lightbox Video

### ISSUE THREAD

**Issue by mburns1216** [archetyped/slb-addons#38]
## Description of issue
Embedded videos will not open up in the lightbox window

## Details

* URL of page exhibiting the issue: http://massamp.com/?page_id=111
* Web Browser(s) that exhibit the issue: Google Chrome
* Simple Lightbox Version: 2.5.2
* Active theme: Rigel by Theme Forest
* Other plugins installed: Akismet, Contact Form 7, Go Daddy Quick Setup, Jetpack by WordPress.com, LayerSlider WP, Post Expirator, Sidekick, Simple Lightbox, Simple Lightbox: Video Handler, WordPress Reset, WP101 Video Tutorials, WPBakery Visual Composer

**Comment by archetyped** [comment]
Hi, embedded players already have the video loaded to play on the page itself.  To open the video in the lightbox, a **link** to the video must be added to the page so that there is something for visitors to click on.

Example:
```html
<a href="https://www.youtube.com/watch?v=Eqz3-IGttrQ">Watch Video</a>
```

Of course, a link can also contain an image if you prefer to display a thumbnail image for visitors to click on.
