### ISSUE TITLE
[Video / Feedback]: Presale question

### ISSUE THREAD

**Issue by yogoeasy** [archetyped/slb-addons#46]
## My Feedback

Hi, 

Now I am using this plugin in my website: Advanced Responsive Video Embedder

So all my videos was inserted with shortcodes like:
[youtube id="aEXMIK0XjBA"] & [vimeo id="121431164"]

I just want to make sure that If I buy your video addon, do I need to change all the shortcode into normal video link like https://www.youtube.com/watch?v=123456

Besides, I saw your demo is shown as a link. Is there any options to change the text or use screenshot instead?

**Comment by archetyped** [comment]
Hi, it looks like that plugin embeds the video player on the page.  SLB's video add-on is helpful for people who want to avoid the overhead and loading time of embedded video players, as a video is only loaded once a visitor actually clicks a link to view a particular video.

If you want to display your videos in a lightbox instead of loading the embedded video players directly on the page, you would need to use links instead.  This way, when the link is clicked, SLB can display them in a lightbox.

SLB works with standard links, allowing you to customize the link as desired with WordPress' post editor.  This means you can use any text or image (e.g. screenshot, etc.) desired for a link.
