### ISSUE TITLE
[Video / Request]: 

### ISSUE THREAD

**Issue by marthaSplatterHead** [archetyped/slb-addons#59]
## Description of feature/request
lightbox loads on page low on page and when I click to next image or video it pushes down again

## This feature would be used to
sorry wrong not a request an Issue

**Comment by archetyped** [comment]
Hi, this is what the video add-on should be doing.  If you have purchased the Video add-on and are experiencing an issue, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with the Video add-on?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by marthaSplatterHead** [comment]
Ya it's still broken, but I decided not to hand the client broken unsupported plugins, I went with a better source, thanks?

**Comment by archetyped** [comment]
Hi, a request for the necessary details to evaluate and resolve your issue was made after receiving your support request, but there was no response.  Unfortunately, there is not much that can be done without this information.

Nonetheless, I'm glad you found a solution that works for you.  If you are interested in resolving the issue your were experiencing with the video add-on in the future, please provide the previously-requested details and I would be glad to reopen this ticket and take a look.

Thanks.
